### ISSUE TITLE
Inquiry: Flatpak or other for distribution to other distros?

### ISSUE THREAD

**Issue by rik-shaw** [endlessm/eos-knowledge-lib#1654]
Endless continues to do great things and in my location we could really benefit from the offline knowledge apps but aren't able to consider a full switch to EndlessOS at this time.

We are working in many minority communities around the world often with limited / no internet access and would love to be able to have a replacement for the pirated Win7 MS Encarta encyclopedia tool that is prevalent.  In the past we used Kiwix to provide Wikipedia offline but this is too big and not curated toward our ESL audiences.  Thus the Endless knowledge apps would be ideal for us to distribute to our users.

So is there any ability to distribute these apps (framework + content) to other Linux system?  Flatpak or other?  If needing to build from source is it fairly straight-forward?  I couldn't quite understand the process I would need to follow from your readme.  Thanks for any help.

We aren't as technically advanced and rely on .deb distribution (Ubuntu-based systems using a PPA) so that would be the best for us in the short-term.  We have a process to distribute updates from one machine to others called Wasta-Offline, which is a basic script with a zenity frontend that (source machine) takes a user's cache and uses  dpkg-scanpackages to generate a local repository on a USB stick and (target machine) moves around a user's sources.list* in order to use the local repository.  https://sites.google.com/site/wastalinux/wasta-applications/wasta-offline

Here is our main website: www.wastalinux.org

Here is our github repository: https://github.com/wasta-linux

**Comment by nedrichards** [comment]
@rik-shaw I'll allow my colleagues to answer the rest of your questions but I just wanted to follow up on `aren't able to consider a full switch to EndlessOS at this time.` if you have time I'd love to know about some of the barriers that are standing in your way there, and if we can help you through them - feel free to ping an email to nick with a domain name of endlessm.com if you have a moment.

**Comment by ptomato** [comment]
Hi @rik-shaw, thanks for your inquiry! Wasta Linux looks quite interesting, I wasn't aware of it before.

The apps, such as Encyclopedia, are shipped with Endless OS and are not open source, so I'm afraid we can't help you there. However, it should be quite possible to create your own offline knowledge apps with Wikipedia content. We have a [walkthrough](http://endlessm.github.io/eos-knowledge-lib/docs/master/tutorial/index.html) on this topic. It's currently missing its last chapter, but that will be published in a matter of days.

I'd also encourage you to join our [community forum](https://community.endlessos.com/). You might be able to share your experiences with others who are bundling their own content.

**Comment by ptomato** [comment]
@rik-shaw I'm happy to inform you that the [walkthrough](http://endlessm.github.io/eos-knowledge-lib/docs/master/tutorial/index.html) is now completely published! I'm assuming this answers your question, please feel free to contact me if you need anything else.
